#pragma once

#include <Eigen/Dense>
#include <cstddef>
#include <vector>

#include <libint2/cxxapi.h>

namespace miniqc {

// Dense four-index tensor with independent dimensions:
// T(i,j,k,l) -> data_[(((i*d1 + j)*d2 + k)*d3 + l)]
// Learning implementation for MP2 AO->MO transformations.
class Tensor4DRect {
public:
    Tensor4DRect() = default;
    Tensor4DRect(std::size_t d0, std::size_t d1, std::size_t d2, std::size_t d3);

    std::size_t dim0() const { return d0_; }
    std::size_t dim1() const { return d1_; }
    std::size_t dim2() const { return d2_; }
    std::size_t dim3() const { return d3_; }
    std::size_t size() const { return data_.size(); }

    double* data() { return data_.data(); }
    const double* data() const { return data_.data(); }

    double& operator()(std::size_t i, std::size_t j, std::size_t k, std::size_t l) {
        return data_[index(i, j, k, l)];
    }

    double operator()(std::size_t i, std::size_t j, std::size_t k, std::size_t l) const {
        return data_[index(i, j, k, l)];
    }

    std::size_t index(std::size_t i, std::size_t j, std::size_t k, std::size_t l) const {
        return (((i * d1_ + j) * d2_ + k) * d3_ + l);
    }

private:
    std::size_t d0_ = 0;
    std::size_t d1_ = 0;
    std::size_t d2_ = 0;
    std::size_t d3_ = 0;
    std::vector<double> data_;
};

struct MP2Options {
    bool verbose = true;

    // V3 no longer stores the full AO ERI tensor. The largest default
    // intermediate is typically t1(o,N,N,N), so guard by estimated memory.
    // Set <= 0 to disable this safety check.
    double max_intermediate_mb = 8192.0;
};

struct MP2Result {
    double correlation_energy = 0.0;
    double total_energy = 0.0;
    std::size_t nbf = 0;
    std::size_t nocc = 0;
    std::size_t nvir = 0;
};

// Direct first-index AO->MO transformation:
// t1(i,nu,lam,sig) = sum_mu C(mu,i) (mu nu | lam sig)
// The AO ERI shell block is generated by Libint, immediately contracted into
// t1, and discarded. No dense AO ERI tensor is stored.
Tensor4DRect build_t1_direct_from_libint(const libint2::BasisSet& basis,
                                         const Eigen::MatrixXd& C,
                                         int nocc,
                                         const MP2Options& options = MP2Options{});

// Complete the remaining three half-transformations:
// t1(o,N,N,N) -> t2(o,v,N,N) -> t3(o,v,o,N) -> ovov(o,v,o,v)
Tensor4DRect transform_t1_to_ovov(Tensor4DRect t1,
                                  const Eigen::MatrixXd& C,
                                  int nocc,
                                  const MP2Options& options = MP2Options{});

MP2Result compute_rhf_mp2_energy(const libint2::BasisSet& basis,
                                 const Eigen::MatrixXd& C,
                                 const Eigen::VectorXd& eps,
                                 int nocc,
                                 double hf_total_energy,
                                 const MP2Options& options = MP2Options{});

}  // namespace miniqc
